scientific-python/repo-review

.github/dependabot.yml
.github/workflows/ci.yml
.pre-commit-config.yaml
docs/webapp.js
pyproject.toml
src/scikit_hep_repo_review/__init__.py
src/scikit_hep_repo_review/ratings/flake8.py
src/scikit_hep_repo_review/ratings/general.py
src/scikit_hep_repo_review/ratings/github.py
src/scikit_hep_repo_review/ratings/mypy.py
src/scikit_hep_repo_review/ratings/precommit.py
src/scikit_hep_repo_review/ratings/pyproject.py

- fix: include [skipped] in webapp
- fix: clean up and expand the text on the checks
- fix: name check was broken
- chore: make repo pass it's own checks
- chore: nicer webapp text in a couple of places

fix: bettter msgs, issue with name

---

.github/CONTRIBUTING.md
.github/dependabot.yml
.github/workflows/ci.yml
.pre-commit-config.yaml
README.md
docs/index.html
docs/webapp.js
src/scikit_hep_repo_review/ratings/precommit.py

- feat: add prettier/blacken-docs
- style: run pre-commit

feat: prettier/blacken-docs

---

src/scikit_hep_repo_review/ratings/precommit.py
src/scikit_hep_repo_review/ratings/pyproject.py

- fix: support pinned bugbear
- fix: broken filterwarnings check

fix: a couple of mistakes

---

docs/webapp.js

Noticed this was hard to share in a convo with @frank1010111. Now you can copy the URL after searching.

fix(webapp): show changed URL when running

---

src/scikit_hep_repo_review/ratings/github.py

Signed-off-by: Henry Schreiner <henryschreineriii@gmail.com>

fix: change check for dependabot GHA

---

src/scikit_hep_repo_review/__init__.py

Needed for the change to Dependabot.

chore: bump to verison 0.4.0

---

.github/workflows/ci.yml
.pre-commit-config.yaml
docs/index.html
docs/webapp.js
pyproject.toml
src/scikit_hep_repo_review/ghpath.py
src/scikit_hep_repo_review/processor.py
src/scikit_hep_repo_review/ratings/mypy.py

chore: update & include py311

---

README.md
pyproject.toml
src/scikit_hep_repo_review/processor.py
src/scikit_hep_repo_review/ratings/general.py
src/scikit_hep_repo_review/ratings/github.py
src/scikit_hep_repo_review/ratings/mypy.py
src/scikit_hep_repo_review/ratings/precommit.py
src/scikit_hep_repo_review/ratings/pyproject.py
src/scikit_hep_repo_review/ratings/ruff.py
tests/test_checks.py

- refactor: entry points for fixtures
- refactor: entry point function for ratings

refactor: entry points

---

.devcontainer/devcontainer.json

Follow up to #44, I deleted the post command by mistake. Adding a little more possibly useful setup.

fix(dev): devcontainer post create

---

.github/workflows/ci.yml
pyproject.toml
src/scikit_hep_repo_review/_compat/importlib/resources/abc.py
src/scikit_hep_repo_review/checks/general.py
src/scikit_hep_repo_review/checks/github.py
src/scikit_hep_repo_review/checks/precommit.py
src/scikit_hep_repo_review/checks/ruff.py
src/scikit_hep_repo_review/fixtures.py
src/scikit_hep_repo_review/ghpath.py
src/scikit_hep_repo_review/processor.py
tests/test_checks.py

chore: add 3.12 to classifiers

---

src/scikit_hep_repo_review/__main__.py
tests/test_cmd.py

feat: add html output option

---

src/scikit_hep_repo_review/__init__.py
src/scikit_hep_repo_review/checks/__init__.py
src/scikit_hep_repo_review/families.py
src/scikit_hep_repo_review/fixtures.py
src/scikit_hep_repo_review/ghpath.py
src/scikit_hep_repo_review/processor.py
tests/test_checks.py
tests/test_fixtures.py

Moving stuff out of processor.

refactor: move functions to files that make more sense

---

src/scikit_hep_repo_review/processor.py

fix: produce the correct error message

---

src/repo_review/checks.py
src/repo_review/processor.py
tests/test_checks.py

Support for dynamic error messages.

feat: dynamic error messages

---

.pre-commit-config.yaml
noxfile.py
pyproject.toml
src/repo_review/__main__.py
src/repo_review/fixtures.py
src/repo_review/processor.py
tests/test_fixtures.py
tests/test_self.py
tests/test_utilities/pyproject.py
tests/test_utilities/pyproject.toml

Includes a bugfix and more testing.

feat: support root / package dir seperation

---

.github/workflows/cd.yml
.github/workflows/ci.yml

ci: prepare dist

---

README.md
src/repo_review/__main__.py
src/repo_review/checks.py
src/repo_review/processor.py
tests/test_checks.py

Adding `--select` / `tool.repo-review.select`.

feat: add select

---

src/repo_review/__main__.py
src/repo_review/processor.py

feat: exit codes

---

.github/workflows/ci.yml
noxfile.py
pyproject.toml
src/repo_review/__main__.py
tests/test_self.py
tests/test_utilities/pyproject.py
tests/test_utilities/pyproject.toml

The URL is shown in rich/html output (should already be present in json).

fix: URL visible in results

---

src/repo_review/processor.py

Makes the URL creation a little easier.

feat: allow name sub in URL

---

docs/index.html
docs/webapp.js
noxfile.py
pyproject.toml
tests/test_self.py

Needs https://github.com/scientific-python/cookie/pull/166 to get some of the URLs right.

fix: update webapp and tests for sp-repo-review

---

docs/index.html
docs/index.md
docs/webapp.js
docs/webapp.md
src/repo_review/__main__.py
src/repo_review/html.py

Support for setting dependencies when loading the webapp. Adding docs for webapp.
Moved the `to_html` function to make it accessible for users.
Might be worth making a proper JS package out of this eventually.

fix: webapp supports setting dependencies

---

src/repo_review/__main__.py
src/repo_review/processor.py

This should help with #51, the format would make an easy copy-paste.

feat: add --list to show all checks

---

.pre-commit-hooks.yaml

Like the action, might not be very useful until #40. Possibly even more so, as the action could be informational, while this one has to "fail" the run to print a report!

feat: add pre-commit support

---

.github/workflows/ci.yml
action.yml
pyproject.toml
src/repo_review/__main__.py

Requires plugins to be specified.

feat: add Composite Action

---

README.md
action.yml
docs/checks.md
docs/cli.md
pyproject.toml
src/repo_review/__main__.py
src/repo_review/_compat/typing.py

This replaces `--output` and `--format split` with a more flexible system.

feat: selection for output

---

action.yml
docs/cli.md
docs/plugins.md
src/repo_review/__main__.py
tests/test_cmd.py

fix: stderr never has format codes

---

docs/index.html
docs/plugins.md
docs/webapp.md

Small things I noticed being slightly off.

docs: minor fixes

---

docs/conf.py
pyproject.toml

docs: add version number

---

docs/index.html
docs/webapp.js

Minor cleanup to message, too.

chore: bump sp-repo-review version

---

docs/conf.py
docs/intro.md
pyproject.toml
src/repo_review/processor.py

This is a better description of what it does.

refactor: rename err_markdown to err_as_html

---

docs/changelog.md
docs/conf.py
docs/index.md
pyproject.toml
src/repo_review/processor.py

docs: add changelog

---

.readthedocs.yaml
docs/checks.md
docs/fixtures.md
docs/index.md
docs/programmatic.md
noxfile.py
pyproject.toml
src/repo_review/__main__.py
src/repo_review/checks.py
src/repo_review/families.py
src/repo_review/fixtures.py
src/repo_review/html.py
src/repo_review/processor.py

Better support for listing all, especially from code.
Still needs a few more version added a, and maybe a couple more gettrrs.

feat: better list-all support

---

docs/webapp.js

Support pressing "enter" to go to the next thing.

fix: support enter in form

---

docs/webapp.js

This does a much better job of formatting a Python error message.

fix: format error messages properly

---

docs/conf.py

docs: link to source

---

.github/workflows/ci.yml
.pre-commit-config.yaml
pyproject.toml

Also removing the target version, see https://github.com/scientific-python/cookie/issues/201.

chore: cleanup and bump pre-commit

---

noxfile.py

Noticed this used by packaging.python.org.

chore: use sphinx-autobuild

---

.gitignore
docs/families.md
docs/webapp.js
src/repo_review/__main__.py
src/repo_review/checks.py
src/repo_review/families.py
src/repo_review/html.py
src/repo_review/processor.py
tests/test_families.py
tests/test_self.py
tests/test_utilities/pyproject.py
tests/test_utilities/pyproject.toml

Dynamic families and description support.

feat: family descriptions

---

docs/index.html
docs/webapp.js
pyproject.toml

docs: update for version 0.9

---

docs/index.html
pyproject.toml

fix: Pyodide has pyyaml 6.0.0

---

docs/webapp.js

Signed-off-by: Henry Schreiner <henryschreineriii@gmail.com>

fix(webapp): span wasn't set properly

---

docs/index.html
src/repo_review/processor.py

Quick fix. Only hit with some repos. :(

fix: pass correct self object

---

README.md
docs/conf.py

docs: add more links and some updates

---

README.md
docs/index.html

Signed-off-by: Henry Schreiner <henryschreineriii@gmail.com>

docs: add validate-pyproject

---

.pre-commit-config.yaml
docs/api/repo_review.resources.rst
docs/api/repo_review.rst
pyproject.toml
src/repo_review/resources/__init__.py
src/repo_review/resources/repo-review.schema.json
src/repo_review/schema.py
tests/test_package.py

Can check it's own config too.

feat: add schema and validate-pyproject support

---

docs/cli.md
src/repo_review/__main__.py
src/repo_review/html.py
tests/test_cmd.py

This is really useful when running on multiple repos.

feat: show err only or errskip only

---

README.md
docs/intro.md

docs: improve install suggestions

---

src/repo_review/__main__.py

fix: nicer error message when branch missing

---

.pre-commit-config.yaml
tests/conftest.py
tests/test_checks.py
tests/test_fixtures.py
tests/test_utilities/pyproject.py

See https://github.com/scientific-python/cookie/pull/299.

chore: move to ruff-format

---

pyproject.toml

Adjusting the checks just a bit.

chore: minor checks tweaks

---

docs/index.html
src/repo_review/__main__.py

fix: github path bug (regression in 0.10.1)

---

docs/intro.md

Help with #161, since it seems to be picky about this now.

docs: make TOML valid

---

docs/intro.md

docs: fix pipx link

---

.github/workflows/ci.yml
docs/index.html
pyproject.toml

chore: sp-repo-review bump

---

docs/index.html

This now checks everything in SchemaStore!

docs: use validate-pyproject-schema-store

---

docs/plugins.md

docs: mention Poetry way of doing entry-points

---

.github/workflows/ci.yml
.pre-commit-config.yaml
docs/index.html
docs/plugins.md

Mostly for the schema-store bump on the demo.

chore: bump some versions

---

docs/webapp.js
pyproject.toml
src/repo_review/ghpath.py

feat: integrate pyodide helper

---

pyproject.toml
tests/test_multi.py

See https://github.com/ewels/rich-click/issues/194.

tests: fix rich-click's self-inflicted warnings

---

docs/index.html
docs/webapp.js

chore: bump some webapp versions

---

docs/webapp.js

fix(webapp): Better package listing

---

.github/ISSUE_TEMPLATE/new-issue.md

docs: new issue template

---

.github/release.yml
pyproject.toml

- **ci: make changelog generation smarter**
- **chore: remove old suppression**

ci: changelog generation

---

docs/index.html

Same as https://github.com/scientific-python/cookie/pull/462. Might help #232.

chore: bump repo-review deps

---

src/repo_review/resources/repo-review.schema.json
tests/test_package.py

First step for https://github.com/scientific-python/repo-review/issues/216 - allow object form in addition to array form.

fix: support object structure in schema

---

.pre-commit-config.yaml
pyproject.toml

chore: use maintained fork of prettier

---

.readthedocs.yaml

The printout was in the wrong environment.

ci: fix docs ci job

---

.github/workflows/ci.yml
docs/index.html
pyproject.toml

Bumping to recently released sp-repo-review.

chore: update cookie

---

src/repo_review/processor.py

This is https://github.com/abravalheri/validate-pyproject/issues/197, and fixes https://github.com/scientific-python/cookie/issues/386.

fix: warn and correct a modified fixture

---

pyproject.toml

Make it easier to run coverage.

chore: support running coverage

---

.github/workflows/cd.yml
.github/workflows/ci.yml

ci: tighten up permissions a bit

---

docs/index.html
docs/webapp.js

docs: bump webapp for 0.12.1

---

docs/webapp.js

Yet another follow-up improvement, on top of #263. This adds "HEAD"  to the dropdown for the WebAssembly demo for `repo-review`, which resolves to and returns the same results as the default branch.

(web app): also support `HEAD` in the branch selector

---

.github/workflows/ci.yml
.pre-commit-config.yaml
docs/index.html
tests/test_package.py

chore: bump to sp-repo-review 2025.05.02 in tests and webapp

---

.github/workflows/ci.yml
pyproject.toml

ci: test on Python π beta 1

---

src/repo_review/__main__.py

Better error message, see #266. Same return code.

fix: better error message if bad URL

---

README.md
action.yml

Bumping the action to use 3.13+.

chore: bump the action to 3.13

---

docs/index.html
docs/webapp.md

chore: bump pyodide to 0.27.6

---

docs/index.html

chore: bump webapp to 0.12.2

---

.pre-commit-config.yaml
pyproject.toml
src/repo_review/__main__.py

See https://github.com/ewels/rich-click/issues/300.

fix: support rich-click 1.9+ on Windows
