scientific-python/repo-review

.pre-commit-config.yaml
Motivated by https://github.com/scikit-hep/scikit-hep.github.io/issues/227 and complimentary to PR https://github.com/scikit-hep/scikit-hep.github.io/pull/231.
* Update pre-commit/pre-commit-hooks to v4.3.0
* Add the 'name-tests-test' pre-commit hooks which verifies that test files under `tests/` conform to `pytest` naming conventions.
- Use the `--pytest-test-first` option to match the `test_.*\.py` naming convention.
=> feat: Add 'name-tests-test' to pre-commit hooks

.flake8, .pre-commit-config.yaml, pyproject.toml, src/scikit_hep_repo_review/__main__.py, src/scikit_hep_repo_review/ghpath.py, src/scikit_hep_repo_review/ratings/flake8.py, src/scikit_hep_repo_review/ratings/general.py, src/scikit_hep_repo_review/ratings/pyproject.py, tests/test_package.py
Able to do this due to 0.0.250+ (https://github.com/charliermarsh/ruff/pull/3047)  supporting match statements! :)
=> chore: move to using Ruff

src/scikit_hep_repo_review/ratings/ruff.py
This was missing, causing a fail instead of a skip.
=> fix: ruff requirement missing

.devcontainer/devcontainer.json, .pre-commit-config.yaml
Adding the config for a Python 3.11 container to develop repo-review :) Needed to remove a check from `tomli` on the version of Python so that it worked on 3.11 as well. Addresses #43
=> Add devcontainer

src/scikit_hep_repo_review/processor.py
Feel free to make this consistent with the rest of the package. I ran out of time at the airport. Part 1 of #41 (second part is output formal options).
```python
from scikit_hep_repo_review.processor import process, results_dict_to_json
from pathlib import Path
r = process(Path("."))
s = results_simple_dict(r)
import json
with open("zzz.json", "w") as fout:
json.dump(s, fout)
with open("zzz.json", "r") as fin:
dd = json.loads(json.load(fin))
```
=> feat: simplify result for json

src/scikit_hep_repo_review/__main__.py, src/scikit_hep_repo_review/processor.py
Follow up to #46. Fixes a bug and adds output format option. Closes #41.
=> feat: json format output & a fix

.github/workflows/ci.yml, .pre-commit-config.yaml, noxfile.py, pyproject.toml, src/scikit_hep_repo_review/__main__.py, src/scikit_hep_repo_review/_compat/tomllib.py, src/scikit_hep_repo_review/fixtures.py, src/scikit_hep_repo_review/ghpath.py, src/scikit_hep_repo_review/processor.py, src/scikit_hep_repo_review/ratings/__init__.py, src/scikit_hep_repo_review/ratings/pyproject.py, tests/test_checks.py, tests/test_cmd.py, tests/test_package.py
Starting ignores and adding a bit of testing and refactoring. Will close #40.
Other changes:
* Pulling out the pyproject fixture into built in fixtures (similar to the package fixture). (Preparation for the upcoming split)
* Some typing updates
Currently this supports ignoring the string code or the entire code.
Planned (later PR): fixtures need entry point. Family as attribute (sorted). Maybe some way to sort families. Check/rating unify language.
=> feat: adding ignores

README.md, pyproject.toml, src/scikit_hep_repo_review/checks/github.py, src/scikit_hep_repo_review/checks/precommit.py, src/scikit_hep_repo_review/fixtures.py, src/scikit_hep_repo_review/processor.py, tests/test_checks.py, tests/test_fixtures.py
By applying the topological sort to fixtures, they now can depend on each other (like pytest); while this is nice for consistently, the main new feature comes when computing the check getter functions, which now accept fixtures. This means checks can be dynamic based on the project (such as having different sets of checks for different build backends). This also now caches the fixture output automatically, removing the need for the functools caching. One downside is that modifying the return value of a fixture is UB, but with the cache, it probably was before too.
I'm very happy with the new system. It adds the feature I wanted while simplifying and increasing consistency.
=> feat: topological graph for fixtures, too

README.md, src/scikit_hep_repo_review/checks/__init__.py, src/scikit_hep_repo_review/checks/general.py, src/scikit_hep_repo_review/checks/github.py, src/scikit_hep_repo_review/checks/mypy.py, src/scikit_hep_repo_review/checks/precommit.py, src/scikit_hep_repo_review/checks/pyproject.py, src/scikit_hep_repo_review/checks/ruff.py, src/scikit_hep_repo_review/processor.py
This makes the checks normal objects. The collection function can therefore configure them as normal objects if needed.
=> refactor: checks as objects

src/scikit_hep_repo_review/processor.py
=> fix: strip paragraph tags when converting to markdown

src/repo_review/checks.py, src/repo_review/processor.py, tests/test_checks.py
=> feat: support for URLs

.github/CONTRIBUTING.md, docs/checks.md, docs/cli.md, docs/families.md
=> docs: filling out a bit more

docs/index.html, docs/index.md, docs/intro.md, docs/plugins.md
=> docs: some getting started info

action.yml, docs/cli.md, docs/index.html, docs/plugins.md, src/repo_review/__main__.py
This flips the meaning of stderr/stdout, making stdout the one that is good for redirection, and stderr the one that is expected to show up on the console.
- fix: nicer form for making GHA
- chore: mark public api in `__main__`
=> refactor: stderr/stdout

.pre-commit-config.yaml, pyproject.toml, src/repo_review/processor.py, tests/test_fixtures.py, tests/test_utilities/pyproject.py
See https://github.com/scientific-python/cookie/pull/200.
=> chore: ruff moved to astral-sh

src/repo_review/processor.py
Notices that new lines around the message show up here.
=> fix: newlines in help line

docs/checks.md, docs/fixtures.md, src/repo_review/processor.py, tests/test_checks.py
Drop running '.format' on dynamic strings. It's hard to ensure they don't have `{}` in them, and you can access this info when building the string yourself. Added a special `name` fixture that allows easy access to the name of the current check.
=> feat: drop formatting of dynamic messages

docs/plugins.md
Based on recent work adding repo-review to validate-pyproject.
=> docs: add some info about making tests for plugins

src/repo_review/__main__.py, tests/test_cmd.py
Special case passing `<path>/pyproject.toml`, to make it easier to loop over a directory with mixed repos.
=> feat: allow passing the path to pyroject.toml

src/repo_review/__main__.py, src/repo_review/html.py, src/repo_review/processor.py, tests/conftest.py, tests/test_cmd.py, tests/test_multi.py, tests/test_self.py
~~JSON is not working correctly yet.~~ Needs some tests.
This takes 3.5 seconds to check every repo in scikit-hep (using all-repos to clone beforehand). While a manual loop took 11.1 seconds, due to needing to reload Python process every time. :)
To run:
```bash
all-repos-clone
cd output/<name>
repo-review */pyproject.toml --show=err --format html > output.html
```
~~I've noticed the way HTML works, it can't print non-existent families that have descriptions.~~ Fixed. I think for now this makes the most sense, since you want to see the report-style descriptions.
=> feat: allow running on multiple directories at once

src/repo_review/__main__.py, src/repo_review/html.py
Drops the color printout for html & json. Rich adds spaces, making it about 5-10 bigger in number of chars (which can cause it to go past the 65K char limit for GitHub comments), and it also wraps, which makes JSON unparsable if there's a long string (like a URL). This happens even if you redirect to a file (only color codes are stripped, not wrapping or whitespace). This lets us drop our workarounds. Someone can send json to jq if they need color.
Followup to #134.
=> fix: drop Rich color printout for html & JSON

src/repo_review/checks.py, tests/test_checks.py
Small feature to allow the command line to override a config file. Close #136.
=> fix: support '*' for select

.github/workflows/ci.yml, docs/index.html, pyproject.toml
=> chore: use sp-repo-review 2023.11.17 for webapp

src/repo_review/html.py
For long description, this was messing up the name column. This should be better.
Noticed in https://github.com/scikit-hep/vector/pull/408.
=> fix: better wrapping in name column

src/repo_review/processor.py
Easy mistake for a plugin to make.
=> fix: better error if requires is not a set

src/repo_review/__main__.py
The YAML format produces unreadable code in light mode with the default theme. This produces good code in light mode, and somewhat readable code in dark mode. I think it's a bug that this one code class changes color with the terminal theme, while all the others colors (and background) do not.
=> fix: use default (light) theme for code

tests/test_cmd.py
=> tests: do not assume the folder is named repo-review

docs/api/repo_review.rst, docs/plugins.md, src/repo_review/checks.py, src/repo_review/processor.py, src/repo_review/testing.py, tests/test_package.py
Should make writing tests for plugins easier.
=> feat: testing function

src/repo_review/testing.py, tests/test_package.py
=> feat: extra testing helper

tests/test_depends.py
=> tests: add an extra test file

.readthedocs.yaml
Trying https://github.com/readthedocs/readthedocs.org/issues/11289. Drops build time from 44 seconds to 21 seconds, finishing equal to or faster than the GHA jobs!
=> ci: faster readthedocs

.github/workflows/ci.yml, pyproject.toml, src/repo_review/__main__.py, tests/test_multi.py, tests/test_package.py
Working on https://github.com/scientific-python/cookie/pull/474 (and therefore https://github.com/scientific-python/cookie/issues/473). I think I know how to fix it, but first trying to reproduce in CI. Like there, we were setting PYTHONUTF8, which likely hides the issue.
=> fix: ensure utf-8 encoding if something else is default and unset

.devcontainer/devcontainer.json, action.yml
=> chore: use 3.12 by default for action

src/repo_review/__main__.py
=> feat: add a --versions option to view all plugin versions

README.md, docs/checks.md, docs/cli.md, docs/families.md, docs/intro.md
Found while reading the documentation.
* `get_familes()` -> `get_families()`
* `it's` -> `its`
* `markdown` -> `Markdown`
* Duplicated word
* "a/an" agreements
I also ran [`typos`](https://github.com/crate-ci/typos) and [codespell](https://github.com/codespell-project/codespell) against the entire repo and they found no other issues.
=> Fix spelling and grammar typos

src/repo_review/__main__.py
This eliminates a bright white background color that renders for Markdown code blocks.
This change was tested on light and dark terminal backgrounds and does not force a background color in either case.
Fixes #249
----
> ![image](https://github.com/user-attachments/assets/e7a3f5ad-39cf-4ee1-bc10-d0943809bd99)
> ![image](https://github.com/user-attachments/assets/1a2b20a5-9500-41a4-a276-9395e3077940)
=> Use `ansi_light` for syntax highlighting

.github/CONTRIBUTING.md, .pre-commit-config.yaml, .readthedocs.yaml, pyproject.toml
`uv run` works. Some duplication due to Hatch not supporting PEP 735.
=> chore: better integration with uv run

README.md, src/repo_review/__main__.py, src/repo_review/processor.py
Add `--extend-*` options to not override pyproject.toml config.
=> feat(cli): extend pyproject lists

README.md, docs/intro.md, src/repo_review/__main__.py, src/repo_review/checks.py, src/repo_review/html.py, src/repo_review/processor.py, tests/test_self.py, tests/test_utilities/pyproject.py, tests/test_utilities/pyproject.toml
Fix #216. If something is skipped with a description, it will be shown with the reason. It's a new field (usually blank) for json, and is added to HTML and terminal outputs.
<h3>Documentation</h3>
<table>
<tr><th>?</th><th nowrap="nowrap">Name</th><th>Description</th></tr>
<tr style="color: green;">
<td><span role="img" aria-label="Passed">&#9989;</span></td>
<td nowrap="nowrap">RTD100</td>
<td><a href="https://learn.scientific-python.org/development/guides/docs#RTD100">Uses ReadTheDocs (pyproject config)</a></td>
</tr>
<tr style="color: green;">
<td><span role="img" aria-label="Passed">&#9989;</span></td>
<td nowrap="nowrap">RTD101</td>
<td><a href="https://learn.scientific-python.org/development/guides/docs#RTD101">You have to set the RTD version number to 2</a></td>
</tr>
<tr …
=> feat: support reasons for ignores

docs/index.html, docs/webapp.js, src/repo_review/html.py, src/repo_review/processor.py
Now that 0.12 is on PyPI, support can be added here.
=> fix: webapp support 0.12's skip reasons, add md_as_html method

docs/api/repo_review.resources.rst, docs/api/repo_review.rst, docs/index.html
This pull request updates Pyodide to version 0.27.3 that we released today (https://pyodide.org/en/stable/project/changelog.html#version-0-27-3). It does not have much to note except a few new packages and that iOS support that was broken since 0.27.1 (which has been restored now).
Also, judging from https://github.com/henryiii/validate-pyproject-schema-store/releases and https://validate-pyproject.readthedocs.io/en/latest/changelog.html, I don't think there is any major breakage to worry about.
- Updated Pyodide to version 0.27.3
- Updated ``validate-pyproject`` to version 0.23.0
- Updated ``validate-pyproject-schema-store`` to version 2025.2.24
=> chore: bump to Pyodide version 0.27.3 and update dependencies

docs/api/repo_review.resources.rst, docs/api/repo_review.rst, docs/index.html, docs/webapp.js
> [!TIP]
> This change has been made on top of the changes in #261, but is more or less separate from them.
This pull request adds support in the repo-review web app for both branches and tags as refs when selecting a GitHub repository to run the tool on.
- Added GitHub API integration to fetch both branches and tags for selected repositories
- The URL parameter handling has been modified to track the reference type. The branches are shown first in the autocomplete dropdown, and tags come later.
- A fallback has been included for common branches when API requests fail (`main`/`develop`/`stable`/etc.)
=> feat: [web app] support both branches and tags in the reference selector

docs/webapp.js
As a follow-up PR to #262, this PR alters the repo-review web app; it sorts "main", "master", "develop", or "stable" branches in that order, whichever of them exist(s) and shows them before any other branches. Also, branches and tags show up in alphabetical order.
=> fix(web app): always show commonly-used branch names at the top

.github/workflows/ci.yml, pyproject.toml
Hatch just needs to run from 3.13 or older.
=> ci: run on Ubuntu/windows on 3.14
